- name: Install Kubernetes Python client
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
    update_cache: true

- name: Check Helm
  ansible.builtin.command: helm version --short
  register: helm_check
  changed_when: false
  failed_when: false

- name: Download Helm installer
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: "0755"
  when: helm_check.rc != 0

- name: Install Helm
  ansible.builtin.command: /tmp/get_helm.sh --version {{ helm_version }}
  when: helm_check.rc != 0
