all:
  vars:
    ansible_user: limhong
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  hosts:
    master01:
      ansible_host: 34.97.251.162
      ip: 10.174.0.3
      access_ip: 10.174.0.3
    master02:
      ansible_host: 35.240.163.246
      ip: 10.148.0.15
      access_ip: 10.148.0.15
    master03:
      ansible_host: 35.198.247.169
      ip: 10.148.0.16
      access_ip: 10.148.0.16
    worker01:
      ansible_host: 34.101.165.146
      ip: 10.184.0.10
      access_ip: 10.184.0.10
    worker02:
      ansible_host: 34.50.94.194
      ip: 10.184.0.11
      access_ip: 10.184.0.11

  children:
    kube_control_plane:
      hosts:
        master01:
        master02:
        master03:

    kube_node:
      hosts:
        worker01:
        worker02:

    etcd:
      hosts:
        master01:
        master02:
        master03:

    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
